---
- hosts: server
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the mysql container
      docker_container:
        name: bookstore_db
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: onlinebookstore
        volumes:
          - ./setup/CreateDatastore.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
          - 3306:3306
    - name: Start the app container
      docker_container:
        name: bookstore
        image: "azizur013/bookstore:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8008:8080
 
